rng:
    build: rng
    ports:
      - "8001:80"

hasher:
    build: hasher
    ports:
      - "8002:80"

webui:
    build: webui
    links:
      - redis
    ports:
      - "8000:80"
    volumes:
      - "./webui/files/:/files/"

redis:
    image: cailloumajor/redis-armhf

worker:
    build: worker
    links:
      - rng
      - hasher
      - redis

